/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hibernatedemo;


import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.hibernate.cfg.Configuration;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.Date;

public class App {
   

    public static void main(String[] args) throws IOException {
    	System.out.println("Project Started");
//		SessionFactory factory=new Configuration().configure().buildSessionFactory();
		
		Configuration cfg=new Configuration();
		cfg.configure("hibernate.cfg.xml");

		StandardServiceRegistryBuilder builder=new StandardServiceRegistryBuilder().applySettings( cfg.getProperties());
		
		SessionFactory factory=cfg.buildSessionFactory(builder.build());
		
		//Creating Student
		Student student =new Student();
		
		student.setId(52);
		student.setName("Ritik");
		student.setCity("Himachal");
		
		//Creating object of Address in main app
		Address address=new Address();
		
		address.setStreet("Street-1");
		address.setCity("Chandigarh");
		address.setOpen(true);
		address.setAddedDate(new Date());
		address.setX(242.343); //It will not import x as it is Transient from database
		
		//Reading Image 
		FileInputStream file= new FileInputStream("src/main/java/b.png");
		byte[] data=new byte[file.available()];
		file.read(data);
		address.setImage(data);
		
		
		
		System.out.println(address);
		System.out.println(student);
		
		Session session= factory.openSession();
		session.beginTransaction();
		session.save(student);
		session.save(address);
		session.getTransaction().commit();
		session.close();
    }
		
}
